export const defaultBoard = [
  { id: 0, name: "Старт", type: "start", action: "collect", amount: 200, img: "https://cdn-icons-png.flaticon.com/128/11103/11103647.png" },

  {
    id: 1,
    name: "Подгориця",
    type: "property",
    color: "",
    price: 60,
    rent: 2,
    owner: null,
    country: "Чорногорія",
    city: "Медитеран",
    img: "https://flagcdn.com/me.svg",
  },
  { id: 2, name: "Скриня громади", type: "chest", color: "#ddf3f7", gift: 500, img: "https://cdn-icons-png.flaticon.com/128/1651/1651898.png" },
  {
    id: 3,
    name: "Цетинє",
    type: "property",
    color: "",
    price: 60,
    rent: 4,
    owner: null,
    country: "Чорногорія",
    city: "Балтійський",
    img: "https://flagcdn.com/me.svg",
  },
  { id: 4, name: "Податок на прибуток", type: "tax_income", amount: 200, img: "https://cdn-icons-png.flaticon.com/128/13990/13990769.png" },

  {
    id: 5,
    name: "Залізниця Редінг",
    type: "railroad",
    price: 200,
    rent: 25,
    owner: null,
    color: "",
    img: "https://cdn-icons-png.flaticon.com/512/3448/3448339.png",
  },

  {
    id: 6,
    name: "Торонто",
    type: "property",
    color: "",
    price: 100,
    rent: 6,
    owner: null,
    country: "Канада",
    city: "Орієнтал",
    img: "https://flagcdn.com/ca.svg",
  },
  { id: 7, name: "Шанс", type: "chance", color: "#fff4b6", img: "https://cdn-icons-png.flaticon.com/128/8286/8286876.png" },
  {
    id: 8,
    name: "Монреаль",
    type: "property",
    color: "",
    price: 100,
    rent: 6,
    owner: null,
    country: "Канада",
    city: "Вермонт",
    img: "https://flagcdn.com/ca.svg",
  },
  {
    id: 9,
    name: "Ванкувер",
    type: "property",
    color: "",
    price: 120,
    rent: 8,
    owner: null,
    country: "Канада",
    city: "Коннектикут",
    img: "https://flagcdn.com/ca.svg",
  },

  { id: 10, name: "В'язниця ", type: "jail", color: "#cdb4b4", img: "https://cdn-icons-png.flaticon.com/128/189/189489.png" },

  {
    id: 11,
    name: "Париж",
    type: "property",
    color: "",
    price: 140,
    rent: 10,
    owner: null,
    country: "Франція",
    city: "Сент-Чарльз",
    img: "https://flagcdn.com/fr.svg",
  },
  {
    id: 12,
    name: "Електростанція",
    type: "utility",
    price: 150,
    rentMultiplier: 4,
    owner: null,
    color: "",
    img: "https://cdn-icons-png.flaticon.com/128/16035/16035521.png",
  },
  {
    id: 13,
    name: "Ліон",
    type: "property",
    color: "",
    price: 140,
    rent: 10,
    owner: null,
    country: "Франція",
    city: "Штат",
    img: "https://flagcdn.com/fr.svg",
  },
  {
    id: 14,
    name: "Марсель",
    type: "property",
    color: "",
    price: 160,
    rent: 12,
    owner: null,
    country: "Франція",
    city: "Вірджинія",
    img: "https://flagcdn.com/fr.svg",
  },

  {
    id: 15,
    name: "Залізниця Пенсильванія",
    type: "railroad",
    price: 200,
    rent: 25,
    owner: null,
    color: "",
    img: "https://cdn-icons-png.flaticon.com/512/3448/3448339.png",
  },

  {
    id: 16,
    name: "Рим",
    type: "property",
    color: "",
    price: 180,
    rent: 14,
    owner: null,
    country: "Італія",
    city: "Сент-Джеймс",
    img: "https://flagcdn.com/it.svg",
  },
  { id: 17, name: "Скриня громади", type: "chest", color: "#ddf3f7", gift: 500, img: "https://cdn-icons-png.flaticon.com/128/1651/1651898.png" },
  {
    id: 18,
    name: "Мілан",
    type: "property",
    color: "",
    price: 180,
    rent: 14,
    owner: null,
    country: "Італія",
    city: "Теннессі",
    img: "https://flagcdn.com/it.svg",
  },
  {
    id: 19,
    name: "Флоренція",
    type: "property",
    color: "",
    price: 200,
    rent: 16,
    owner: null,
    country: "Італія",
    city: "Нью-Йорк",
    img: "https://flagcdn.com/it.svg",
  },

  { id: 20, name: "🅿️ Безкоштовна стоянка", type: "parking" },

  {
    id: 21,
    name: "Мадрид",
    type: "property",
    color: "",
    price: 220,
    rent: 18,
    owner: null,
    country: "Іспанія",
    city: "Кентуккі",
    img: "https://flagcdn.com/es.svg",
  },
  { id: 22, name: "Шанс", type: "chance", color: "#fff4b6", img: "https://cdn-icons-png.flaticon.com/128/8286/8286876.png" },
  {
    id: 23,
    name: "Барселона",
    type: "property",
    color: "",
    price: 220,
    rent: 18,
    owner: null,
    country: "Іспанія",
    city: "Індіана",
    img: "https://flagcdn.com/es.svg",
  },
  {
    id: 24,
    name: "Севілья",
    type: "property",
    color: "",
    price: 240,
    rent: 20,
    owner: null,
    country: "Іспанія",
    city: "Іллінойс",
    img: "https://flagcdn.com/es.svg",
  },

  {
    id: 25,
    name: "Залізниця Бен-Авеню",
    type: "railroad",
    price: 200,
    rent: 25,
    owner: null,
    img: "https://cdn-icons-png.flaticon.com/512/3448/3448339.png",
  },

  {
    id: 26,
    name: "Берлін",
    type: "property",
    color: "",
    price: 260,
    rent: 22,
    owner: null,
    country: "Німеччина",
    city: "Атлантік",
    img: "https://flagcdn.com/de.svg",
  },
  {
    id: 27,
    name: "Гамбург",
    type: "property",
    color: "",
    price: 260,
    rent: 22,
    owner: null,
    country: "Німеччина",
    city: "Вентнор",
    img: "https://flagcdn.com/de.svg",
  },
  {
    id: 28,
    name: "Водоканал",
    type: "utility",
    price: 150,
    rentMultiplier: 4,
    owner: null,
    img: "https://cdn-icons-png.flaticon.com/128/4497/4497450.png",
  },
  {
    id: 29,
    name: "Мюнхен",
    type: "property",
    color: "",
    price: 280,
    rent: 24,
    owner: null,
    country: "Німеччина",
    city: "Марвін Гарденс",
    img: "https://flagcdn.com/de.svg",
  },

  { id: 30, name: "Йде до в'язниці", type: "go_to_jail", color: "#cdb4b4", img: "https://cdn-icons-png.flaticon.com/128/6732/6732862.png" },

  {
    id: 31,
    name: "Лондон",
    type: "property",
    color: "",
    price: 300,
    rent: 26,
    owner: null,
    country: "Велика Британія",
    city: "Пасифік",
    img: "https://flagcdn.com/gb.svg",
  },
  {
    id: 32,
    name: "Манчестер",
    type: "property",
    color: "",
    price: 300,
    rent: 26,
    owner: null,
    country: "Велика Британія",
    city: "Північна Кароліна",
    img: "https://flagcdn.com/gb.svg",
  },
  { id: 33, name: "Скриня короля", type: "chest", color: "#ddf3f7", gift: 1000, img: "https://cdn-icons-png.flaticon.com/128/18036/18036705.png" },
  {
    id: 34,
    name: "Бірмінгем",
    type: "property",
    color: "",
    price: 320,
    rent: 28,
    owner: null,
    country: "Велика Британія",
    city: "Пенсильванія",
    img: "https://flagcdn.com/gb.svg",
  },

  {
    id: 35,
    name: "Залізниця Шорт-Лайн",
    type: "railroad",
    price: 200,
    rent: 25,
    owner: null,
    img: "https://cdn-icons-png.flaticon.com/512/3448/3448339.png",
  },

  { id: 36, name: "Шанс", type: "chance", color: "#fff4b6", img: "https://cdn-icons-png.flaticon.com/128/8286/8286876.png" },
  {
    id: 37,
    name: "Токіо",
    type: "property",
    color: "dark-blue",
    price: 350,
    rent: 35,
    owner: null,
    country: "Японія",
    city: "Парк-Плейс",
    img: "https://flagcdn.com/jp.svg",
  },
  { id: 38, name: "Розкішний податок", type: "tax", amount: 1000, img: "https://cdn-icons-png.flaticon.com/128/3257/3257334.png" },
  {
    id: 39,
    name: "Осака",
    type: "property",
    color: "",
    price: 400,
    rent: 800,
    owner: null,
    country: "Японія",
    city: "Бродвей",
    img: "https://flagcdn.com/jp.svg",
  },
];
